name: carrot-kinoite-nvidia
description: CarrotManMatt's personal custom linux image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
    # - type: files
    #   files:
    #     - usr: /usr
    #         # copies config/files/usr into your image's /usr.
    #         # put configuration files you want in /etc/ on a booted system
    #         # in /usr/etc/ in the image. read more in files module reference.

    - type: akmods
      install:
          - openrgb

    - type: rpm-ostree
      install:
          - micro
          - fastfetch
          - asciidoctor
          - python3.12
          - python3-pip
          - langpacks-en
          - nvidia-container-toolkit
          - nu
          - bootc
          - libva-nvidia-driver
      remove:
          - firefox
          - firefox-langpacks
          - nano
          - nano-default-editor
          - apr-util-openssl
          - apr-util-lmdb
          - apr
          - apr-util
          - toolbox
          - htop
          - nvtop
          - tmux
          - google-noto-sans-sundanese-fonts
          - google-noto-sans-javanese-fonts
          - google-noto-sans-cjk-fonts
          - google-noto-sans-balinese-fonts
          - kate
          - kwrite
          - kate-krunner-plugin
          - kate-plugins

    - type: rpm-ostree
      repos:
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      install:
          - nvidia-vaapi-driver

    - type: rpm-ostree
      repos:
          - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      install:
          - starship

    - type: script
      scripts:
          - install-poetry.sh
          - bootc-update-bootloader.sh
          - hide-default-kde-apps.sh
          - disable-secondary-screen-in-sddm.sh
          - add-twingate-package-repo.sh

    - type: rpm-ostree
      install:
          - twingate

    - type: default-flatpaks
      notify: true
      user:
          repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
          repo-name: flathub-user
          repo-title: "Flathub"  # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          remove:
              - org.gnome.eog
              - com.github.tchx84.Flatseal
          install:
            - com.google.Chrome
            - com.discordapp.Discord
            - org.linuxshowplayer.LinuxShowPlayer
            - com.valvesoftware.Steam
            - com.heroicgameslauncher.hgl
            - com.jetbrains.PyCharm-Professional
            - com.getpostman.Postman
            - com.jetbrains.IntelliJ-IDEA-Ultimate
            - com.jetbrains.GoLand
            - org.nickvision.tubeconverter
            - org.audacityteam.Audacity
            - org.gimp.GIMP
            - org.blender.Blender
            - com.obsproject.Studio
            - com.spotify.Client
            - com.nextcloud.desktopclient.nextcloud
            - com.bitwarden.desktop
            - org.openstreetmap.josm
            - com.stremio.Stremio
            - org.videolan.VLC
            - us.zoom.Zoom
            - io.github.mimbrero.WhatsAppDesktop
            - com.usebottles.bottles
            - io.github.dvlv.boxbuddyrs
      system:
          repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
          repo-name: flathub-system
          repo-title: "Flathub (System)"  # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          remove:
              - org.gnome.eog
              - io.github.flattool.Warehouse
              - com.github.tchx84.Flatseal

    - type: chezmoi
      repository: "--ssh CarrotManMatt"

    - type: fonts
      fonts:
          nerd-fonts:
              - FiraCode

    - type: signing
