name: carrot-kinoite-nvidia
description: CarrotManMatt's personal custom linux image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
    - type: files
      files:
        - source: system
          destination: /
          # Copies files/system/** into your image's /**.
          # Put configuration files you want in /etc/ on a booted system in files/system/usr/etc/ in the image.
          # Read more in files module reference.

    - type: akmods
      install:
          - openrgb

    - type: rpm-ostree
      install:
          - micro
          - fastfetch
          - langpacks-en
          - nvidia-container-toolkit
          - nextcloud-client-dolphin
          - nu
          - bootc
          - libva-nvidia-driver
          - ksshaskpass
      remove:
          - firefox
          - firefox-langpacks
          - nano
          - nano-default-editor
          - apr-util-openssl
          - apr-util-lmdb
          - apr
          - apr-util
          - toolbox
          - htop
          - nvtop
          - tmux
          - google-noto-sans-sundanese-fonts
          - google-noto-sans-javanese-fonts
          - google-noto-sans-cjk-fonts
          - google-noto-sans-balinese-fonts
          - kate
          - kwrite
          - kate-krunner-plugin
          - kate-plugins

    - type: rpm-ostree
      repos:
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      install:
          - nvidia-vaapi-driver

    - type: rpm-ostree
      repos:
          - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      install:
          - starship

    - type: script
      scripts:
          - add-twingate-package-repo.sh

    - type: rpm-ostree
      install:
          - twingate

    - type: default-flatpaks
      notify: true
      user:
          repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
          repo-name: flathub-user
          repo-title: "Flathub"  # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          remove:
              - org.gnome.eog
              - io.github.flattool.Warehouse
              - com.github.tchx84.Flatseal
              - com.jetbrains.IntelliJ-IDEA-Ultimate
              - com.jetbrains.PyCharm-Professional
              - com.jetbrains.GoLand
          install:
              - com.google.Chrome
              - com.discordapp.Discord
              - org.linuxshowplayer.LinuxShowPlayer
              - com.valvesoftware.Steam
              - com.heroicgameslauncher.hgl
              - com.getpostman.Postman
              - org.nickvision.tubeconverter
              - org.audacityteam.Audacity
              - org.gimp.GIMP
              - org.blender.Blender
              - com.obsproject.Studio
              - com.spotify.Client
              - com.nextcloud.desktopclient.nextcloud
              - com.bitwarden.desktop
              - org.openstreetmap.josm
              - org.videolan.VLC
              - us.zoom.Zoom
              - io.github.mimbrero.WhatsAppDesktop
              - com.usebottles.bottles
              - io.github.dvlv.boxbuddyrs
              - com.mojang.Minecraft
              - org.openrgb.OpenRGB
      system:
          repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
          repo-name: flathub-system
          repo-title: "Flathub (System)"  # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          remove:
              - org.gnome.eog
              - io.github.flattool.Warehouse
              - com.github.tchx84.Flatseal
              - com.google.Chrome
              - com.discordapp.Discord
              - org.linuxshowplayer.LinuxShowPlayer
              - com.valvesoftware.Steam
              - com.heroicgameslauncher.hgl
              - com.jetbrains.PyCharm-Professional
              - com.getpostman.Postman
              - com.jetbrains.IntelliJ-IDEA-Ultimate
              - com.jetbrains.GoLand
              - org.nickvision.tubeconverter
              - org.audacityteam.Audacity
              - org.gimp.GIMP
              - org.blender.Blender
              - com.obsproject.Studio
              - com.spotify.Client
              - com.nextcloud.desktopclient.nextcloud
              - com.bitwarden.desktop
              - org.openstreetmap.josm
              - com.stremio.Stremio
              - org.videolan.VLC
              - us.zoom.Zoom
              - io.github.mimbrero.WhatsAppDesktop
              - com.usebottles.bottles
              - io.github.dvlv.boxbuddyrs

    - type: chezmoi
      repository: "--ssh CarrotManMatt"

    - type: fonts
      fonts:
          nerd-fonts:
              - FiraCode

    - type: script
      scripts:
          - hide-default-kde-apps.sh

    - type: signing
