name: carrot-kinoite-nvidia
description: CarrotManMatt's personal custom linux image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  # - type: files
  #   files:
  #     - usr: /usr
  #         # copies config/files/usr into your image's /usr.
  #         # put configuration files you want in /etc/ on a booted system
  #         # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    install:
      - micro
      - fastfetch
      - asciidoctor
      - python3.12
      - langpacks-en
    remove:
      - firefox
      - firefox-langpacks
      - nano
      - nano-default-editor
      - apr-util-openssl
      - apr-util-bdb
      - apr
      - apr-util
      - toolbox
      - htop
      - nvtop

  - type: script
    scripts:
      - install-package-pam-pwdfile.sh
      - install-poetry.sh
      - add-twingate-package-repo.sh

  - type: rpm-ostree
    install:
      - twingate

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (System)"  # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      remove:
        - org.gnome.eog
      install:
        - com.google.Chrome
        - com.discordapp.Discord
        - org.linuxshowplayer.LinuxShowPlayer
        - com.valvesoftware.Steam
        - com.heroicgameslauncher.hgl
        - com.jetbrains.PyCharm-Professional
        - com.getpostman.Postman
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.jetbrains.GoLand
        - org.nickvision.tubeconverter
        - org.audacityteam.Audacity
        - org.gimp.GIMP
        - org.blender.Blender
        - com.obsproject.Studio
        - com.spotify.Client
        - com.nextcloud.desktopclient.nextcloud
        - com.bitwarden.desktop
        - org.openstreetmap.josm
        - com.stremio.Stremio
        - org.videolan.VLC
        - us.zoom.Zoom
        - io.github.mimbrero.WhatsAppDesktop
        - com.usebottles.bottles
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-user
      repo-title: "Flathub"

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  - type: signing
