name: carrot-kinoite-nvidia
description: CarrotManMatt's personal custom linux image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  # - type: files
  #   files:
  #     - usr: /usr
  #         # copies config/files/usr into your image's /usr.
  #         # put configuration files you want in /etc/ on a booted system 
  #         # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    install:
      - micro
      - fastfetch
    remove:
      - firefox
      - firefox-langpacks
      - nano
      - nano-default-editor
      # - vim
      - apr
      - apr-util
      - toolbox

  # - type: rpm-ostree
  #   repos:
  #     - 
  #   install:
  #     - libpam-pwdfile

  - type: script
    scripts: 
      - add-twingate-package-repo.sh

  - type: rpm-ostree
    install:
      - twingate

  - type: default-flatpaks
    notify: true
    system:
      remove:
        - org.gnome.eog
      install:
        - com.google.Chrome
        - com.discordapp.Discord
        - org.linuxshowplayer.LinuxShowPlayer
        - com.valvesoftware.Steam
        - com.jetbrains.PyCharm-Professional
        - com.getpostman.Postman
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.jetbrains.GoLand
        - org.nickvision.tubeconverter
        - org.audacityteam.Audacity
        - org.gimp.GIMP
        - org.blender.Blender
        - com.obsproject.Studio
        - com.spotify.Client
        - com.nextcloud.desktopclient.nextcloud
        - com.bitwarden.desktop
        - org.openstreetmap.josm
        - md.obsidian.Obsidian
        - com.stremio.Stremio
        - org.videolan.VLC
        - us.zoom.Zoom
        - io.github.mimbrero.WhatsAppDesktop
        - org.mixxx.Mixxx

  - type: signing
